# Generated by Django 4.2.7 on 2023-11-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_name', models.CharField()),
                ('hub_url', models.URLField()),
                ('poll_interval', models.IntegerField(default=600)),
            ],
            options={
                'db_table': 'hubs',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.URLField()),
                ('article_title', models.CharField()),
                ('article_text', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('author_username', models.CharField()),
                ('author_url', models.URLField()),
                ('hub_id', models.ForeignKey(db_column='hub_id', on_delete=django.db.models.deletion.CASCADE, to='parser_configurator.hub')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
